-- ============================================================
-- BOOTSTRAP: Config Screen + Optimizer V6 Migration
-- Project Aquarius | 2026-02-15
-- Run in Snowsight — one step at a time
-- ============================================================
-- NOTE: EXPOSURE_SOURCE and IMPRESSION_JOIN_STRATEGY are already
-- correctly populated. This script does NOT modify those values.
--
-- Routing key: IMPRESSION_JOIN_STRATEGY
--   ADM_PREFIX  = row-level (Paramount, COUNT DISTINCT)
--   PCM_4KEY    = pre-aggregated (Class B, SUM)
--   DIRECT_AG   = web pixel direct (no impression join)
--
-- EXPOSURE_SOURCE (data type taxonomy, untouched):
--   IMPRESSION  = impression-based attribution
--   WEB         = web pixel attribution
--   OOH         = out-of-home measurement
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE QUORUMDB;


-- ============================================================
-- STEP 1: Verify current config state (read-only check)
-- ============================================================

-- Confirm IMPRESSION_JOIN_STRATEGY is populated correctly
SELECT IMPRESSION_JOIN_STRATEGY, EXPOSURE_SOURCE,
       COUNT(*) as total,
       SUM(CASE WHEN CONFIG_STATUS='ACTIVE' THEN 1 ELSE 0 END) as active,
       COUNT(DISTINCT AGENCY_ID) as agencies
FROM QUORUMDB.BASE_TABLES.REF_ADVERTISER_CONFIG
GROUP BY IMPRESSION_JOIN_STRATEGY, EXPOSURE_SOURCE
ORDER BY total DESC;

-- Confirm optimizer agencies have the right strategy
SELECT AGENCY_ID, IMPRESSION_JOIN_STRATEGY, EXPOSURE_SOURCE,
       COUNT(*) as advertisers,
       SUM(CASE WHEN HAS_IMPRESSION_TRACKING THEN 1 ELSE 0 END) as has_impressions,
       SUM(CASE WHEN HAS_STORE_VISIT_ATTRIBUTION THEN 1 ELSE 0 END) as has_store_visits
FROM QUORUMDB.BASE_TABLES.REF_ADVERTISER_CONFIG
WHERE AGENCY_ID IN (1480, 1813, 2514, 2459, 2466, 2513, 2564, 2565, 2567, 2568, 2569)
  AND CONFIG_STATUS = 'ACTIVE'
GROUP BY AGENCY_ID, IMPRESSION_JOIN_STRATEGY, EXPOSURE_SOURCE
ORDER BY AGENCY_ID;


-- ============================================================
-- STEP 2: Grant V5 views + config to OPTIMIZER_READONLY_ROLE
-- ============================================================

-- V5 unified visit views
GRANT SELECT ON QUORUMDB.SEGMENT_DATA.V5_ALL_VISITS TO ROLE OPTIMIZER_READONLY_ROLE;
GRANT SELECT ON QUORUMDB.SEGMENT_DATA.V5_STORE_VISITS_ENRICHED TO ROLE OPTIMIZER_READONLY_ROLE;
GRANT SELECT ON QUORUMDB.SEGMENT_DATA.V5_STORE_VISITS_PARAMOUNT TO ROLE OPTIMIZER_READONLY_ROLE;
GRANT SELECT ON QUORUMDB.SEGMENT_DATA.V5_WEB_VISITS_PARAMOUNT TO ROLE OPTIMIZER_READONLY_ROLE;
GRANT SELECT ON QUORUMDB.SEGMENT_DATA.V5_STORE_VISITS_WITH_HOUSEHOLD TO ROLE OPTIMIZER_READONLY_ROLE;

-- Config table (optimizer reads IMPRESSION_JOIN_STRATEGY for routing)
GRANT SELECT ON QUORUMDB.BASE_TABLES.REF_ADVERTISER_CONFIG TO ROLE OPTIMIZER_READONLY_ROLE;

-- Materialized store visits table
GRANT SELECT ON QUORUMDB.BASE_TABLES.STORE_VISITS TO ROLE OPTIMIZER_READONLY_ROLE;

-- Unmapped activity views (config screen reads)
GRANT SELECT ON QUORUMDB.BASE_TABLES.V_UNMAPPED_AD_IMPRESSIONS TO ROLE OPTIMIZER_READONLY_ROLE;
GRANT SELECT ON QUORUMDB.BASE_TABLES.V_UNMAPPED_WEB_PIXELS TO ROLE OPTIMIZER_READONLY_ROLE;
GRANT SELECT ON QUORUMDB.BASE_TABLES.V_POI_BRAND_SEARCH TO ROLE OPTIMIZER_READONLY_ROLE;


-- ============================================================
-- STEP 3: Create CONFIG_ADMIN_ROLE for config API writes
-- ============================================================

CREATE ROLE IF NOT EXISTS CONFIG_ADMIN_ROLE;

-- Read access (same as optimizer — needs to query for autocomplete, validation)
GRANT SELECT ON ALL TABLES IN SCHEMA QUORUMDB.SEGMENT_DATA TO ROLE CONFIG_ADMIN_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA QUORUMDB.SEGMENT_DATA TO ROLE CONFIG_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA QUORUMDB.BASE_TABLES TO ROLE CONFIG_ADMIN_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA QUORUMDB.BASE_TABLES TO ROLE CONFIG_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA QUORUMDB.REF_DATA TO ROLE CONFIG_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA QUORUMDB.DERIVED_TABLES TO ROLE CONFIG_ADMIN_ROLE;

-- Write access for config operations
GRANT INSERT, UPDATE ON QUORUMDB.REF_DATA.PIXEL_CAMPAIGN_MAPPING_V2 TO ROLE CONFIG_ADMIN_ROLE;
GRANT INSERT, UPDATE ON QUORUMDB.DERIVED_TABLES.ADVERTISER_DOMAIN_MAPPING TO ROLE CONFIG_ADMIN_ROLE;
GRANT INSERT, UPDATE ON QUORUMDB.SEGMENT_DATA.SEGMENT_MD5_MAPPING TO ROLE CONFIG_ADMIN_ROLE;
GRANT INSERT, UPDATE ON QUORUMDB.BASE_TABLES.REF_ADVERTISER_CONFIG TO ROLE CONFIG_ADMIN_ROLE;
GRANT INSERT ON QUORUMDB.BASE_TABLES.SEGMENT_METADATA TO ROLE CONFIG_ADMIN_ROLE;

-- Schema USAGE grants (required for INSERT/UPDATE)
GRANT USAGE ON SCHEMA QUORUMDB.SEGMENT_DATA TO ROLE CONFIG_ADMIN_ROLE;
GRANT USAGE ON SCHEMA QUORUMDB.BASE_TABLES TO ROLE CONFIG_ADMIN_ROLE;
GRANT USAGE ON SCHEMA QUORUMDB.REF_DATA TO ROLE CONFIG_ADMIN_ROLE;
GRANT USAGE ON SCHEMA QUORUMDB.DERIVED_TABLES TO ROLE CONFIG_ADMIN_ROLE;
GRANT USAGE ON DATABASE QUORUMDB TO ROLE CONFIG_ADMIN_ROLE;

-- Warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CONFIG_ADMIN_ROLE;

-- Grant to service user (uncomment and replace with your service account)
-- GRANT ROLE CONFIG_ADMIN_ROLE TO USER OPTIMIZER_SVC;


-- ============================================================
-- STEP 4: Verify everything
-- ============================================================

-- Config completeness
SELECT
    COUNT(*) as TOTAL,
    SUM(CASE WHEN EXPOSURE_SOURCE IS NOT NULL THEN 1 ELSE 0 END) as HAS_EXPOSURE_SOURCE,
    SUM(CASE WHEN IMPRESSION_JOIN_STRATEGY IS NOT NULL THEN 1 ELSE 0 END) as HAS_STRATEGY,
    SUM(CASE WHEN HAS_STORE_VISIT_ATTRIBUTION THEN 1 ELSE 0 END) as HAS_STORE_VISITS,
    SUM(CASE WHEN HAS_WEB_VISIT_ATTRIBUTION THEN 1 ELSE 0 END) as HAS_WEB_VISITS,
    SUM(CASE WHEN HAS_IMPRESSION_TRACKING THEN 1 ELSE 0 END) as HAS_IMPRESSIONS
FROM QUORUMDB.BASE_TABLES.REF_ADVERTISER_CONFIG
WHERE CONFIG_STATUS = 'ACTIVE';

-- V5 views returning data
SELECT VISIT_TYPE, COUNT(*) as visits_last_7d
FROM QUORUMDB.SEGMENT_DATA.V5_ALL_VISITS
WHERE VISIT_DATE >= CURRENT_DATE - 7
GROUP BY VISIT_TYPE;

-- Unmapped activity requiring config
SELECT COUNT(*) as unmapped_impressions
FROM QUORUMDB.BASE_TABLES.V_UNMAPPED_AD_IMPRESSIONS
WHERE IMPRESSIONS_30D >= 100;

-- Store visits pipeline healthy
SELECT
    MAX(STORE_VISIT_DATE) as latest_store_visit,
    COUNT(*) as total_rows,
    COUNT(DISTINCT AGENCY_ID) as agencies
FROM QUORUMDB.BASE_TABLES.STORE_VISITS;

-- Grants verification (spot check)
SHOW GRANTS ON QUORUMDB.SEGMENT_DATA.V5_ALL_VISITS;
SHOW GRANTS ON QUORUMDB.BASE_TABLES.REF_ADVERTISER_CONFIG;
SHOW GRANTS TO ROLE CONFIG_ADMIN_ROLE;


-- ============================================================
-- DONE. System is ready for:
--   1. Config API to handle campaign/domain/POI mapping
--      (uses CONFIG_ADMIN_ROLE for writes)
--   2. Optimizer v6 to route by IMPRESSION_JOIN_STRATEGY:
--      ADM_PREFIX → row-level PARAMOUNT_IMPRESSIONS_REPORT_90_DAYS
--      PCM_4KEY   → pre-aggregated CAMPAIGN_PERFORMANCE_REPORT_WEEKLY_STATS
--   3. V5 views providing unified store/web visit data
--   4. STORE_VISITS pipeline running daily via REFRESH_QRM_V4
-- ============================================================
